version: '3'
services:
  discovery:
    image: erw444/discovery
    ports:
      - 8761:8761
  blog-website:
    image: erw444/blog-website  
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka
    depends_on:
      - discovery
  website-frontend:
    image: erw444/website-frontend
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka
    restart: on-failure
    depends_on:
      - discovery
      - blog-website
    ports:
      - 8080:5000