apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: discovery
  name: discovery
spec:
  ports:
  - name: 8080-8761
    port: 8080
    protocol: TCP
    targetPort: 8761
  selector:
    app: discovery
  type: ClusterIP
status:
  loadBalancer: {}
