server:
  port: 5000

zuul:
  routes:
    blog:
      path: /blog/**
      service-id: BLOG
      stripPrefix: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
spring:
  application:
    name: website-frontend